### ISSUE TITLE
Python reference docs are almost empty

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1439]
https://deltares.github.io/Ribasim/reference/python/
Could be due to changes in https://github.com/machow/quartodoc

Possibly related to #219

Edit: I think it is working fine, but we just don't have many docstrings anymore. And currently methods that have docstrings don't seems to get included, so we should look into that. ~~Perhaps best done after #1298.~~

- [x] Fix bug in docstrings
- [x] add info to pages (focus on most important items:

**Comment by Jingru923** [comment]
I added some docstring under Model() class, and quartodoc can show those docstring now, the bug is no longer there.

**Comment by Jingru923** [comment]
When I was working on this issue, I hope that quardoc can collect all the self-defined functions in Model class and show it in API. 

I tried `include_functions` option in `content`, it does nothing. This turns out to be impossible. 

My current conclusion is that we need to list all the functions manually, and later if new functions are added, keep in mind to also add them to API page. I think  we can generate a list of functions in python, and copy paste that list to `quartodoc` in `_quarto.yml`. I couldn't succeed it yet but I believe we can investigate that

**Comment by evetion** [comment]
It might be good to link to an open issue on quartodoc about this, and link to the configuration page, where you got the `include_functions` from.

**Comment by evetion** [comment]
FWIW, after checking the [documentation](https://machow.github.io/quartodoc/get-started/basic-content.html#all-content-options), and [this issue](https://github.com/machow/quartodoc/issues/275#issuecomment-1733945469), we could do this:

```
quartodoc:
  style: pkgdown
  dir: python/reference
  title: API Reference
  package: ribasim
  options:
      include_inherited: true
      include_empty: true
      include_attributes: true
      include_classes: true
      include_functions: true
  sections:
    - title: ribasim
      contents:
        - name: ribasim
          package: null
          include_imports: true
```

The options will make sure to render everything (classes/attributes/etc), while the ribasim section would render everything we export.
