### ISSUE TITLE
Water balance error when saving each timestep

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1853]
`check_water_balance_error` runs on `saveat`, by default once per day. We support writing output for each timestep with

```toml
[solver]
saveat = 0
```

For e.g. the HWS model this fails the water balance check at t=0, whereas it works even with a tiny `saveat = 1` second.

```
┌ Error: Too large water balance error
│   id = Basin #1340
│   balance_error = 84387.34177215189
│   relative_error = 2.0
└ @ Ribasim d:\repo\ribasim\Ribasim\core\src\callback.jl:317
```

Perhaps the check should be disabled for `saveat = 0`? One workaround now is to set large water balance tolerances:

```toml
[solver]
saveat = 0
water_balance_abstol = 1e30 # optional, default 1e-3
water_balance_reltol = 1e20 # optional, default 1e-2
```

Also I see that currently we fail the check if **both** the absolute and relative tolerance is exceeded. Shouldn't this be **either**?
