### ISSUE TITLE
README.md in build misses description

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#1930]
The last release that is ok is v2024.7.0, with this README.md in the builds:

```
# Ribasim CLI

This is a [Julia](https://julialang.org/) project that uses the [Ribasim](https://github.com/Deltares/Ribasim) Julia package, puts a simple command line interface (cli) on top, and packages this into a standalone application using [PackageCompiler.jl](https://github.com/JuliaLang/PackageCompiler.jl).

This enables using Ribasim without having to install Julia, and thus makes it more convenient to use in certain settings where installation must be simple and no interactive Julia session is needed.

If you have installed Julia and Ribasim, a simulation can also be started from the command line as follows:

    julia --eval 'using Ribasim; Ribasim.main("path/to/model/ribasim.toml")'

With a Ribasim CLI build this becomes:

    ribasim path/to/model/ribasim.toml
```

All releases since have this instead:

```
No documentation found.

Binding `build_app` does not exist.
```

The version section is also wrong:
```toml
release = "2024.10.0-128-ge09eeb5"
commit = "https://github.com/Deltares/Ribasim/tree/e09eeb5b9a"
branch = "https://github.com/Deltares/Ribasim/tree/main"
julia_version = "1.10.5"
core_version = "2024.11.0"
```

But that is #1655

**Comment by visr** [comment]
I suggest a shorter and simpler readme like this:

# Ribasim

Ribasim is a water resources model to simulate the physical behavior of a managed open water system based on a set of control rules and a prioritized water allocation strategy.

Usage: `ribasim path/to/model/ribasim.toml`
Documentation: https://ribasim.org/


## Version

This build uses the Ribasim version mentioned below.

```toml
release = "2024.11.0"
commit = "https://github.com/Deltares/Ribasim/tree/e09eeb5b9a"
branch = "https://github.com/Deltares/Ribasim/tree/main"
julia_version = "1.10.5"
```
