### ISSUE TITLE
`ribasim --version` is wrong for releases

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#2040]
Previously we had the issue #1655 that failed the release tests. The tests we fixed, but the issue described in https://github.com/Deltares/Ribasim/issues/1655#issuecomment-2400784264 remains.

The README.md for the v2025.1.0 build states:

```toml
version = "2024.11.0-74-ge2b86cd"
commit = "https://github.com/Deltares/Ribasim/tree/e2b86cdb0d"
branch = "https://github.com/Deltares/Ribasim/tree/main"
```

That commit is the right one: https://github.com/Deltares/Ribasim/tree/e2b86cdb0d. So why is it not recognizing the tag? The release workflow is supposed to trigger on the tag being pushed, as mentioned here: https://ribasim.org/dev/release.html#create-a-new-release. Perhaps that is not the case? Or if it already built the same commit that is later tagged it doesn't build new artifacts or something?
