### ISSUE TITLE
Make a distinction between active and passive river and drainage packages

### ISSUE THREAD

**Issue by Huite** [Deltares/Ribasim#517]
This requires changes in:

* imod-python
* imod_coupler
* iMOD Suite documentation

We should go from:

```toml
[[driver.coupling]]
mf6_model = "inner_model"
mf6_river_packages = ["riv_primary", "riv_secondary"]
mf6_drainage_packages = ["drn_primary"]
```

to:

```diff
[[driver.coupling]]
mf6_model = "inner_model"
-mf6_river_packages = ["riv_primary", "riv_secondary"]
+mf6_active_river_packages = ["riv_primary"]
+mf6_passive_river_packages = ["riv_secondary"]
-mf6_drainage_packages = ["drn_primary"]
+mf6_active_drainage_packages = ["drn_primary"]
+mf6_passive_drainage_packages = []
```

However, due to #514, we will require dictionaries mapping the package keys to their respective exchange files:

```toml
[[driver.coupling]]
mf6_model = "inner_model"
mf6_active_river_packages = {"riv_primary" = "riv-1.tsv"}
mf6_passive_river_packages = {"riv_secondary" = "riv-2.tsv"}
mf6_active_drainage_packages = {"drn_primary" = "drn-1.tsv"}
mf6_passive_drainage_packages = {}
```
