### ISSUE TITLE
Add tag to build metadata

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#557]
The README.md in the builds contains some metadata on the source of the build. For a nightly build that looks like:

```toml
version = "0.1.0"
commit = "https://github.com/Deltares/Ribasim/tree/c3df3f39ce"
branch = "https://github.com/Deltares/Ribasim/tree/main"
julia_version = "1.9.3"
```

When building from a tag, it'd be nice to have the tag there. Right now it shows `branch = "https://github.com/Deltares/Ribasim/tree/HEAD"` when building from a tag, which isn't helpful.

https://github.com/Deltares/Ribasim/blob/v2023.0.1/build/create_binaries/add_metadata.jl#L47
