### ISSUE TITLE
Default results design

### ISSUE THREAD

**Issue by visr** [Deltares/Ribasim#799]
Currently the entire results section is optional, with the following defaults:

```toml
[results]
# These results files are always written
flow = "results/flow.arrow"       # optional, default "results/flow.arrow"
basin = "results/basin.arrow"     # optional, default "results/basin.arrow"
control = "results/control.arrow" # optional, default "results/control.arrow"
allocation = "results/allocation.arrow" # optional, default "results/allocation.arrow"
compression = "zstd"             # optional, default "zstd", also supports "lz4"
compression_level = 6            # optional, default 6
```

In https://github.com/Deltares/Ribasim/issues/638#issuecomment-1746283362 I suggested to stop using default paths, so it is always explicit from the TOML file which files belong to the model, without having to know the defaults. I still like having this explicit, though it does mean that the minimal TOML becomes bigger (not really a problem), and that in Ribasim Python you need to add `results = ribasim.Results(flow = "results/flow.arrow", basin = "results/basin.arrow", ...)`

One related thing is that we now always write all 4 files. If e.g. control and allocation are not part of the model, Arrow files with 0 rows are written to disk. If we decide to require explicit paths for the results, we have a way to turn off output that we are not interested in. That would be nice to support in the future as we may add some more output that is not always interesting or cheap to write.

I'm not sure anymore what's the best design here and would like some input from others. If we go for explicit paths that's a breaking change that would be best to make soon.

**Comment by visr** [comment]
After discussing with @evetion and @Hofer-Julian we suggest the following structure:

```toml
input_dir = "."  # required
results_dir = "results"  # required

# database = "database.gpkg"  # removed, always input_dir / "database.gpkg"

[results]
# flow = "results/flow.arrow"             # removed, always results_dir / "flow.arrow"
# basin = "results/basin.arrow"           # removed, always results_dir / "basin.arrow"
# control = "results/control.arrow"       # removed, always results_dir / "control.arrow"
# allocation = "results/allocation.arrow" # removed, always results_dir / "allocation.arrow"
compression = "zstd"                    # optional, default "zstd", also supports "lz4"
compression_level = 6                   # optional, default 6
```

- [ ] In ribasim-python, always write to and from `path/to/ribasim.toml`, never a directory
- [ ] Change the `results_dir` default to `"results"`
- [ ] Remove `database` TOML key
- [ ] Remove all four results file paths from TOML
