### ISSUE TITLE
Pydantic model_dump(exclude_unset=True, ...) causes model.write to ignore mutation

### ISSUE THREAD

**Issue by Huite** [Deltares/Ribasim#811]
Here's an MWE:

```python
import ribasim_testmodels

model = ribasim_testmodels.trivial.trivial_model()
model.solver.saveat = 86400.0
model.write("here")
```

If you now check the TOML, I'd expect to see a non-default saveat entry, but instead:

```toml
starttime = 2020-01-01 00:00:00
endtime = 2021-01-01 00:00:00
database = "database.gpkg"
```

I believe this is due to the (expected) behavior of exlude_unset, see also:
https://github.com/pydantic/pydantic/discussions/5749

Creating a new object does work, probably because the solver entry is detected as being set by pydantic?

```python
model = ribasim_testmodels.trivial.trivial_model()
model.solver = ribasim.Solver(saveat=86400.0)
model.write("here")
```

TOML:

```toml
starttime = 2020-01-01 00:00:00
endtime = 2021-01-01 00:00:00
database = "database.gpkg"

[solver]
saveat = 86400.0
```

Given that this seems expected behavior by pydantic, I'm not sure it's easy to fix (without dirty hacks).

A pragmatic solution might be something like this:

```python
model.solver = ribasim.solver.update(saveat=86400.0)
```

The update method just returns a new object.

You can argue this is consistent with how you're supposed to work with pandas and xarray, where the `inplace` operations are mostly discouraged or removed; although you might as well make the object immutable in that case to avoid confusion?
